name: pytorch
channels:
  - http://conda.anaconda.org/gurobi
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _pytorch_select=0.2=gpu_0
  - blas=1.0=mkl
  - ca-certificates=2020.6.24=0
  - certifi=2020.6.20=py37_0
  - cffi=1.14.1=py37he30daa8_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.5=cuda10.0_0
  - intel-openmp=2020.1=217
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - mkl=2020.1=217
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.1.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.0=py37hfd86e86_0
  - openssl=1.1.1g=h7b6447c_0
  - pip=20.2.2=py37_0
  - pycparser=2.20=py_2
  - python=3.7.7=hcff3b4d_5
  - pytorch=1.4.0=cuda100py37h75a84eb_0
  - readline=8.0=h7b6447c_0
  - setuptools=49.6.0=py37_0
  - six=1.15.0=py_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.34.2=py37_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.10.0
    - aiohttp==3.6.2
    - astunparse==1.6.3
    - async-timeout==3.0.1
    - attrs==20.2.0
    - cachetools==4.1.1
    - chardet==3.0.4
    - click==7.1.2
    - contractions==0.0.25
    - cython==0.29.21
    - editdistance==0.5.3
    - emoji==0.6.0
    - empath==0.89
    - fastbpe==0.1.0
    - filelock==3.0.12
    - gast==0.3.3
    - gensim==3.8.3
    - google-auth==1.22.0
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - h5py==2.10.0
    - idna==2.10
    - importlib-metadata==2.0.0
    - joblib==0.16.0
    - keras==2.4.3
    - keras-preprocessing==1.1.2
    - markdown==3.2.2
    - multidict==4.7.6
    - nltk==3.5
    - numpy==1.18.5
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - packaging==20.4
    - pandas==1.1.1
    - portalocker==2.0.0
    - protobuf==3.13.0
    - py-rouge==1.1
    - pyahocorasick==1.4.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==2.4.7
    - pyphen==0.9.5
    - python-dateutil==2.8.1
    - pytz==2020.1
    - pyyaml==5.3.1
    - regex==2020.7.14
    - requests==2.24.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - sacrebleu==1.4.13
    - sacremoses==0.0.43
    - scikit-learn==0.23.2
    - scipy==1.5.2
    - sentence-transformers==0.3.4
    - sentencepiece==0.1.91
    - smart-open==2.2.0
    - tensorboard==2.3.0
    - tensorboard-plugin-wit==1.7.0
    - tensorflow==2.3.1
    - tensorflow-estimator==2.3.0
    - termcolor==1.1.0
    - textsearch==0.0.17
    - textstat==0.6.2
    - threadpoolctl==2.1.0
    - tokenizer==2.4.0
    - tokenizers==0.8.1rc1
    - tqdm==4.48.2
    - transformers==3.0.2
    - typing-extensions==3.7.4.3
    - unidecode==1.1.1
    - urllib3==1.25.10
    - werkzeug==1.0.1
    - wrapt==1.12.1
    - yarl==1.6.0
    - zipp==3.2.0
prefix: /home/rajdeep/.conda/envs/pytorch

